version: '3.8'

services:
  web:
    image: php:8.3-apache
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - database
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

  database:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: akabo
      MYSQL_DATABASE: akabo
      MYSQL_USER: akabo
      MYSQL_PASSWORD: akabo
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database

volumes:
  db_data: